 function getStateAbbrev(state){
     state=state.toString().replace(/\s/g,'').toUpperCase();
     const statepairs={ALABAMA:'AL',ALASKA:'AK',ARIZONA:'AZ',ARKANSAS:'AR',AMERICANSAMOA:'AS',CALIFORNIA:'CA',COLORADO:'CO',CONNECTICUT:'CT',DELAWARE:'DE',DISTRICTOFCOLUMBIA:'DC',FLORIDA:'FL',GEORGIA:'GA',GUAM:'GU',HAWAII:'HI',IDAHO:'ID',ILLINOIS:'IL',INDIANA:'IN',IOWA:'IA',KANSAS:'KS',KENTUCKY:'KY',LOUISIANA:'LA',MAINE:'ME',MARYLAND:'MD',MASSACHUSETTS:'MA',MICHIGAN:'MI',MINNESOTA:'MN',MISSISSIPPI:'MS',MISSOURI:'MO',MONTANA:'MT',NEBRASKA:'NE',NEVADA:'NV',NEWHAMPSHIRE:'NH',NEWJERSEY:'NJ',NEWMEXICO:'NM',NEWYORK:'NY',NORTHCAROLINA:'NC',NORTHDAKOTA:'ND',NORTHERNMARIANAISLANDS:'CM',OHIO:'OH',OKLAHOMA:'OK',OREGON:'OR',PENNSYLVANIA:'PA',PUERTORICO:'PR',RHODEISLAND:'RI',SOUTHCAROLINA:'SC',SOUTHDAKOTA:'SD',TENNESSEE:'TN',TEXAS:'TX',TRUSTTERRITORIES:'TT',UTAH:'UT',VERMONT:'VT',VIRGINIA:'VA',VIRGINISLANDS:'VI',WASHINGTON:'WA',WESTVIRGINIA:'WV',WISCONSIN:'WI',WYOMING:'WY'}
     return Object.values(statepairs).includes(state)?state:Object.keys(statepairs).includes(state)?statepairs[state]:null
     
     
 }
 
